live_config_reload = true

[window]
decorations = "full"
opacity = 0.8

[window.padding]
x = 8
y = 8

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 0

[colors.normal]
red = "#ff6969"