[env]
TERM = "xterm-256color"

[window]
decorations = "full"
opacity = 0.8


[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 0

[general]
live_config_reload = true

[terminal.shell]
program = "C:\\Program Files\\PowerShell\\7\\pwsh.exe"
args = ["-NoLogo", "-wd", "C:\\Users\\dan"]

[keyboard]
bindings = [
    { key = "E", mods = "Control", action = "ReceiveChar" }
]
